2025-03-05 03:38:17,190 - INFO - Using default arguments: 1
2025-03-05 03:38:17,191 - INFO - End setInputValues - Finally
2025-03-05 03:38:17,192 - INFO - Valid URL
2025-03-05 03:38:17,192 - INFO - Enter getURLObj
2025-03-05 03:38:17,317 - INFO - Got it: 200 {<Response [200]>}
2025-03-05 03:38:17,317 - INFO - Exit getURLObj
2025-03-05 03:38:17,318 - INFO - Response 200
2025-03-05 03:38:23,749 - INFO - Enter writeObj: /home/jku/git/jksfoTemp/python3/wget2/output.html
2025-03-05 03:38:27,062 - INFO - exiting writeObj: /home/jku/git/jksfoTemp/python3/wget2/output.html - success
2025-03-05 03:39:15,614 - ERROR - An error occurred: 'Logger' object is not callable
2025-03-05 03:39:15,615 - INFO - Main program logic finished.
2025-03-05 03:41:22,378 - INFO - mylogger created.
2025-03-05 03:41:22,381 - INFO - Starting main program logic.
2025-03-05 03:41:25,561 - INFO - Begin setInputValues
2025-03-05 03:41:26,155 - INFO - Using default arguments: 1
2025-03-05 03:41:26,155 - INFO - End setInputValues - Finally
2025-03-05 03:41:26,156 - INFO - Valid URL
2025-03-05 03:41:26,157 - INFO - Enter getURLObj
2025-03-05 03:41:26,296 - INFO - Got it: 200 {<Response [200]>}
2025-03-05 03:41:26,296 - INFO - Exit getURLObj
2025-03-05 03:41:26,297 - INFO - Response 200
2025-03-05 03:41:31,041 - INFO - Enter writeObj: /home/jku/git/jksfoTemp/python3/wget2/output.html
2025-03-05 03:41:34,310 - INFO - exiting writeObj: /home/jku/git/jksfoTemp/python3/wget2/output.html - success
2025-03-05 03:41:36,491 - INFO - Exit writeObj
2025-03-05 03:41:37,689 - INFO - Where is the mylogger error?
2025-03-05 03:41:39,691 - INFO - Should be done, why am I getting a logging error?
2025-03-05 03:41:41,572 - INFO - Main program logic finished.
2025-03-05 11:24:28,985 - INFO - mylogger created.
2025-03-05 11:24:28,988 - INFO - Starting main program logic.
2025-03-05 11:24:34,383 - INFO - Begin setInputValues
2025-03-05 11:24:35,164 - INFO - Using default arguments: 1
2025-03-05 11:24:35,164 - INFO - End setInputValues - Finally
2025-03-05 11:24:35,165 - INFO - Valid URL
2025-03-05 11:24:35,166 - INFO - Enter getURLObj
2025-03-05 11:24:35,291 - INFO - Got it: 200 {<Response [200]>}
2025-03-05 11:24:35,291 - INFO - Exit getURLObj
2025-03-05 11:24:35,292 - INFO - Response 200
2025-03-05 11:24:37,671 - INFO - Enter writeObj: /home/jku/git/jksfoTemp/python3/wget2/output.html
2025-03-05 11:24:37,673 - INFO - exiting writeObj: /home/jku/git/jksfoTemp/python3/wget2/output.html - success
2025-03-05 11:24:37,673 - INFO - Exit writeObj
2025-03-05 11:24:37,674 - INFO - Where is the mylogger error?
2025-03-05 11:24:37,674 - INFO - Should be done, why am I getting a logging error?
2025-03-05 11:24:37,674 - INFO - Main program logic finished.
